/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function WebGLSmile(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/smiley.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.11, -57.86, 56.92]} rotation={[0, 0, -0.01]}>
        <mesh
          geometry={nodes.Smile_1.geometry}
          material={nodes.Smile_1.material}
        />
      </group>
      <mesh
        geometry={nodes.Capsule.geometry}
        material={nodes.Capsule.material}
        position={[30, 13.5, 51.77]}
      />
      <mesh
        geometry={nodes.Capsule1.geometry}
        material={nodes.Capsule1.material}
        position={[-30, 13.5, 51.77]}
      />
      <mesh geometry={nodes.Head.geometry} material={materials.Mat} />
    </group>
  );
}

useGLTF.preload("/smiley.gltf");
